### ISSUE TITLE
I got this

### ISSUE THREAD

**Issue by simonetolomelli** [steffenmllr/node-red-contrib-sonoff-tasmota#16]
RangeError: Maximum call stack size exceeded
![schermata 2018-03-13 alle 17 22 43](https://user-images.githubusercontent.com/33097753/37354999-36da5302-26e3-11e8-90f1-6bbb8619a18f.png)

**Comment by l3d00m** [comment]
This means that something is calling itself infinitely (recursive). This happens because the switch gets the light's state and passes it again to the light which passes it to the switch ...

In the switch you have to disable that the input state should be passed to the output if you're using this setup (the x)
